### ISSUE TITLE
LICENSE file has incorrect name

### ISSUE THREAD

**Issue by christo4ferris** [IBM/rocc-software#1]
The LICENSE file needs to be named "LICENSE" not LICENSE.IBM. Also, it needs to contain the full Apache 2.0 license text, not just the abbreviated header. See e.g. https://github.com/IBM/qiskit-api-py/blob/master/LICENSE

**Comment by seldridge** [comment]
Thanks for bringing this to my attention.

The motivation here was to disambiguate (going forward) on a file-by-file basis which `LICENSE.<X>` it falls under. This isn't at all an issue with this repository, but it is an issue for a separate repository that uses this as a submodule for which IBM is a contributor. 

There's a PR in place for you to verify @christo4ferris with updated per-file header lines pointing at `LICENSE` as opposed to `LICENSE.IBM`.

**Comment by seldridge** [comment]
Fixed with #2
